name: Texcraft CI jobs

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.62.0
          profile: minimal
          override: true

      - name: Build the binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins

      - name: Run the tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          