name: Texcraft CI jobs

on: [push, pull_request]

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.80.0
          profile: minimal
          override: true

      - name: build clox
        run: cd tests/craftinginterpreters && make clox
      # todo
      #- name: Run Clippy
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: clippy
      #    args: --all-targets --all-features

      - name: Build the binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins

      - name: Run the tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      
      - name: E2E tests (from the Crafting Interpreters repo)
        uses: docker/build-push-action@v4
        with:
          file: tests/Dockerfile
          context: .
